version: 2

jobs:
  build:
    docker:
      - image: notnoopci/php:7.1.5-browsers
      - image: selenium/standalone-chrome:3.1.0
    working_directory: ~/sandbox
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Toyko"
    steps:
      - checkout
      - run: composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run:
          command: php -S localhost:8000
          background: true
      - run: ./vendor/bin/codecept build
      - run: ./vendor/bin/codecept run